-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 19:25:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetointegrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetointegrador
-- -----------------------------------------------------
CREATE DATABASE projetointegrador  CHARSET = UTF8 COLLATE = utf8_general_ci;
USE `projetointegrador` ;

-- -----------------------------------------------------
-- Table `projetointegrador`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador`.`Departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetointegrador`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador`.`Tipo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetointegrador`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `sexo` VARCHAR(15) NULL,
  `Departamento_id` INT NOT NULL,
  `Tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Departamento_id`, `Tipo_id`),
  INDEX `fk_Usuario_Departamento1_idx` (`Departamento_id` ASC) ,
  INDEX `fk_Usuario_Tipo1_idx` (`Tipo_id` ASC) ,
  CONSTRAINT `fk_Usuario_Departamento1`
    FOREIGN KEY (`Departamento_id`)
    REFERENCES `projetointegrador`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Tipo1`
    FOREIGN KEY (`Tipo_id`)
    REFERENCES `projetointegrador`.`Tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetointegrador`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(30) NULL,
  `email` VARCHAR(25) NULL,
  `prioridade` VARCHAR(25) NULL,
  `reclamacao` VARCHAR(300) NULL,
  `reportar` ENUM('U', 'D') NOT NULL DEFAULT 'U',
  `ativo` BIT(1) NOT NULL DEFAULT 1,
  `dataAbertura` TIMESTAMP(4) NULL,
  `dataFechamento` TIMESTAMP(4) NULL,
  `lastUpdate` TIMESTAMP(4) NULL,
  `Usuario_id` INT NOT NULL,
  `Usuario_Departamento_id` INT NOT NULL,
  `Usuario_Tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_Usuario1_idx` (`Usuario_id` ASC, `Usuario_Departamento_id` ASC, `Usuario_Tipo_id` ASC) ,
  CONSTRAINT `fk_tickets_Usuario1`
    FOREIGN KEY (`Usuario_id` , `Usuario_Departamento_id` , `Usuario_Tipo_id`)
    REFERENCES `projetointegrador`.`Usuario` (`id` , `Departamento_id` , `Tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;